--테이블 만들기..
/*
규칙, 클래스를 먼저 설계한다.

주의할점 : 자바 9가지 타입(정수4,실수2,불리언1,문자1,문자열,날짜)
            오라클로 4가지로 구분(NUMBER(10,2), VARCHAR2(100),CHAR(10),DATE)
            
            오라클은 가변 사이즈 이다..정해지지 않음.그래서 10이라는 바이트를 준거임
            한글 3바이트임. 넘버는 최대22바이트이다.
*/
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(10)NOT NULL,
    MEMBER_PWD VARCHAR2(10),
    MEMBER_NAME VARCHAR2(10)
);
INSERT INTO MAMBER(MEMBER_ID, MEMBER_PWD, MEMBER_NAME) VALLUES('KKK');
SELECT * FROM MEMBER;


--자료형에 메모리를 저장하는 방법, 유튜브로 보기
--NUMBER 사이즈 개념, VARCHAR,CHAR 차이점 !
--KIMCHI -> VARCHAR2(3)
--자바 형변환INT NUMB = (INT)34.45; ,INTEGER.PARTHINT("234")
SELECT CAST('KIMCHI', AS VARCHAR2(3) FROM DUAL;
CREATE TABLE TEST_VARCHAR2(
    TEMP_DATA VARCHAR2(3)
);
DROP TABLE TEST_VARCHAR2;(TEMP_DATA) VALUES('KIMCHI');
SELECT* FROM TEST_VARCHAR2;

--DATE 날짜 + 숫자 DATE
SELECT SYSDATE AS TODAT , SYSDATE + 10 AS PLUS_10 FROM DUAL;
--DATA 날짜 - 숫자-> DATE
SELECT SYSDATE AS TODAT , SYSDATE - 10 AS PLUS_10 FROM DUAL;
--DATA 날짜 -날짜 -> NUMBER
--TODATE 문자열을 날짜로 변경해주는 함수
--자바 "A"객체 'A'  INT A = 10; ' ', " " 둘 다 씀.
SELECT TO_DATE('2025-09-15 11:47:40','YYYY-MM-DD HH24:MI:SS') -TO_DATE('2025-09-15 11:47:40','YYYY-MM-DD HH24:MI:SS')AS RESULT FROM DUAL;

--4.컬럼주석 
CREATE TABLE MEMBER2(
    MEMBER_ID VARCHAR2(10)
    MEMBER_PWD VARCHAR2(10),
    MEMBER_NAME VARCHAR2(10)
);

COMMENT ON COLUMN MEMBER2.MEMBER2_ID IS '회원아이디';  
COMMENT ON COLUMN MEMBER2.MEMBER2_PWD IS IS '비밀번호';
COMMENT ON COLUMN MEMBER2.MEMBER2_NAME IS '회원이름';

DESC MEMBER2;

--5.*제약조건(CONSTRAINTS) NOT NULL, NULL, PK,UQ,FK,CHECK
--자바에서 NULL STRING NAME = NULL; // 힙 영역에 있는 객체를 어떤것도 가르키고 있지 않다.
--오라클에서는 NULL은 넣지말아라. NOT NULL 값을 넣어라. NOT NULL 제약조건이 걸린다..?
--자바에서 NULL - 아무것도 가리키고 있지 않다.

--NOTNULL 데이터에 NUJLL을 허용하지 않음
--UNIQUE 중복된 값을 허용하지 않음 NULL허용

--6. 제약조건테이블 확인하기
SELECT *
FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'MEMBER';

--CHECK
--7. UNIQUE (절대 중복값이허용되지 않음 , NULL은허용안함
--8.CHECK제약조건
CREATE TABLE USER_CHECK(
GENDER VARCHAR2(10) CHECK(GENDERIN('남','여'))

--**10. FOREIGN KEY
--주 테이블(PK), 서브테이블}(FK)
CREATE TABLE USER_FOREIGNKEY(
USER_NO NUMBER,
USER_ID VARCHAR(20),
USER_PWD VARCHAR(30) NOT NULL,
USER_NAME VARCHAR(30),
GENDER VATCHAR2(10),
PHONE VARCHAR2(30),
EMAIL VARCHAR2(50),
GRADE_CODE NUMBER,
CONSTRAINT PK_FOREIGNKEY_NO PRI


DELETE FROM USER_GRADE WHERE GRADE = 10;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEE_COPY';


--11.SUBQUERY 활용한 TABLE 생성 JOIN
CREATE TABLE EMPLOYEE_COPY
 AS SELECT EMP_ID, EMP_NAME, SALARY, DEPT_TITLE, JOB_NAME
 FROM EMPLOYEE
 LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
 LEFT JOIN JOB USING(JOB_CODE);
 
 SELECT * FROM EMPLOYEE_COPY;